### PR TITLE
Teardown robustness needed in tempest tests

### LINKED ISSUE #43: Tempest test teardown hardening needed
Our tempest tests are not immune to test interactions. We need to harden the test teardown process as much as we can currently, allowing tests to properly teardown resources created by the test through the proper channels (neutron REST api). This just means making the cleanup calls for the tests and test suites be more flexible in the way it detects and moves around errors.

There will be a second fix for hardening process, which will likely mean resetting the neutron database after all 'proper' cleanup has been performed. But that work is not included in this issue.

### PR DESCRIPTION
**Pull request by pjbreaux**
@szakeri 

Issues:
Fixes #43

Problem:
Our tempest tests are not immune to test interactions. We need to harden
the test teardown process as much as we can currently, allowing tests to
properly teardown resources created by the test through the proper
channels (neutron REST api). This just means making the cleanup calls
for the tests and test suites be more flexible in the way it detects and
moves around errors.

Note that these teardown fixes are being put in for the tempest api tests currently, since that is where most problems occur.

Analysis:
Moved teardown logic for api tests into the neutron-lbaas repo, so
the driver can benefit from the code as well. This means that two PRs
will be in flight for this change, one to move the logic over to this
repo, and one to remove the logic in the driver.

Tests:
Ran tests against my local fork. Saw an intermittent Bad Status Line
failure in the test_listener_basic scenario test, but I haven't nailed
down the cause, other than bad test assumptions. Will keep an eye on
this in nightly.

### CODE REVIEW

**Comment by pjbreaux** [comment]
@szakeri: this PR must go in first, then we must get the testrunner container updated for the driver nightly tests. Then we can get the PR for the driver in.

**Comment by pjbreaux** [comment]
@szakeri: also, this means that we must get your changes for fixing the neutron-lbaas reference in the driver into mitaka.

**Review by szakeri — APPROVED** [review]
Looks good

**Comment by szakeri** [comment]
@jlongstaf I think we are ready for this change to be merged in

**Pull request merged**
